# Generated by Django 4.0.3 on 2022-03-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goodstype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexgoodsbanner',
            name='image',
        ),
    ]
