# Generated by Django 4.0.3 on 2022-03-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_indexgoodsbanner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='image',
        ),
    ]
