# Generated by Django 4.0.3 on 2022-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_goodssku_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgoodsbanner',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='图片url'),
        ),
    ]
