# Generated by Django 4.0.3 on 2022-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_indexgoodsbanner_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpromotionbanner',
            name='image',
        ),
        migrations.AddField(
            model_name='indexpromotionbanner',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='促销商品图片url'),
        ),
    ]
