# Generated by Django 4.0.3 on 2022-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_goodstype_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='图片url'),
        ),
    ]
