# Generated by Django 4.0.3 on 2022-03-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='test',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试字段'),
        ),
    ]
